#!/usr/bin/env bash

declare -i KEY
KEY=`xinput list | grep -Eio 'Razer Razer Blade Keyboard.*id\=[0-9]{1,2}' |  grep -Eo '[0-9]{1,2}'`
declare -i STATE
STATE=`xinput list-props $KEY|grep 'Device Enabled'|awk '{print $4}'`
if [[ $STATE -eq 1 ]]; then
  xinput disable $KEY && notify-send "Keyboard disabled"
else
  xinput enable $KEY && notify-send "Keyboard enabled"
fi

